name: Deploy App

on: workflow_dispatch

#on:
#    push:
#        branches: [ main ]

jobs:

    deploy:
        runs-on: ubuntu-latest

        name: Build and Deploy to Heroku

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Set up JDK 17
                uses: actions/setup-java@v2
                with:
                    distribution: 'temurin'
                    java-version: '17'
                    cache: 'gradle'

            -   name: Build JAR file with Gradle
                run: ./gradlew web:build -x test --no-daemon

            -   name: Login to Heroku
                env:
                    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                run: heroku container:login

            -   name: Install Heroku Java Plugin
                env:
                    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                run: heroku plugins:install java

            -   name: Deploy to Heroku
                env:
                    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                run: |
                    heroku config:set PYCHATTER_URL='https://gischat-pychatter.herokuapp.com' -a gischat
                    heroku deploy:jar web/build/libs/web.jar -a gischat
