name: Deploy Pychatter

on: workflow_dispatch

#on:
#    push:
#        branches: [ main ]

jobs:

    deploy:
        runs-on: ubuntu-latest

        name: Deploy to Heroku

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Login to Heroku
                env:
                    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                run: heroku container:login

            -   name: Install Heroku Builds Plugin
                env:
                    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                run: heroku plugins:install heroku-builds

            -   name: Deploy to Heroku
                env:
                    HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
                    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
                run: |
                    cd pychatter
                    heroku config:set OPENAI_API_KEY=$OPENAI_API_KEY -a gischat-pychatter
                    heroku builds:create -a gischat-pychatter
